_wandb:
    value:
        cli_version: 0.22.2
        e:
            jodb6w00sm5bdj815hy4tlb3vlupybwd:
                codePath: qwen_qlora_wandb.py
                codePathLocal: qwen_qlora_wandb.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.1"
                disk:
                    /:
                        total: "1013309239296"
                        used: "342596726784"
                email: marshallcnliu@gmail.com
                executable: C:\Users\c1052689\py310env\Scripts\python.exe
                git:
                    commit: f5b0fcdaad1c45bf683cbcf5ba6fa8b5d04f428f
                gpu: NVIDIA RTX A4000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-9f4fd34d-af67-c1f1-8dca-fc51ca411932
                host: PS-PGR-530914
                memory:
                    total: "34054680576"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\c1052689\OneDrive - Newcastle University\CODE\LLM\qwen_qlora_wandb.py
                python: CPython 3.10.11
                root: C:\Users\c1052689\OneDrive - Newcastle University\CODE\LLM
                startedAt: "2025-10-22T15:57:19.601503Z"
                writerId: jodb6w00sm5bdj815hy4tlb3vlupybwd
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 84
                - 98
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 84
                - 98
                - 105
            "3":
                - 13
            "4": 3.10.11
            "5": 0.22.2
            "6": 4.57.1
            "8":
                - 3
            "12": 0.22.2
            "13": windows-amd64
